name: Hello World!

on: 
  push:
    branches:
      - master

jobs:
  hellow_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    step:
      - name: Say date
        run: |
          date
    step:
      - name: Say directory
        run: |
          ls - l
