name: Periodic health check

on:
  push:
    branches:
      - master

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: check deployed url
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://quiet-bayou-16852.herokuapp.com